"""auto

Revision ID: 0dc808c981c6
Revises: 41c55d9a420f
Create Date: 2025-08-03 16:12:08.208863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc808c981c6'
down_revision: Union[str, None] = '41c55d9a420f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    unitcompletionstatus_enum = sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='unitcompletionstatus')
    unitcompletionstatus_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('development_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='unitcompletionstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'development_status')
    # ### end Alembic commands ###
