"""auto

Revision ID: 2c257f025b9f
Revises: b3bf9c823e6a
Create Date: 2025-08-19 17:11:45.119897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c257f025b9f'
down_revision: Union[str, None] = 'b3bf9c823e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('mediafile_user_id_fkey'), 'mediafile', type_='foreignkey')
    op.drop_column('mediafile', 'user_id')
    op.add_column('payment', sa.Column('reason_for_payment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'reason_for_payment')
    op.add_column('mediafile', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('mediafile_user_id_fkey'), 'mediafile', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
