"""auto

Revision ID: 41c55d9a420f
Revises: c995fad7d875
Create Date: 2025-07-28 18:29:09.833190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c55d9a420f'
down_revision: Union[str, None] = 'c995fad7d875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    projectpurpose_enum = sa.Enum(
        'RESIDENTIAL', 'COMMERCIAL', 'MIXED_USE', 'INDUSTRIAL', 'OTHER',
        name='projectpurpose'
    )
    projectpurpose_enum.create(op.get_bind(), checkfirst=True)
    op.execute("UPDATE project SET purpose = 'RESIDENTIAL' WHERE LOWER(purpose) = 'residential'")
    op.alter_column('project', 'purpose',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'MIXED_USE', 'INDUSTRIAL', 'OTHER', name='projectpurpose'),
               existing_nullable=True, postgresql_using="purpose::projectpurpose")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'purpose',
               existing_type=sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'MIXED_USE', 'INDUSTRIAL', 'OTHER', name='projectpurpose'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
