"""auto

Revision ID: 424811927d10
Revises: 0dc808c981c6
Create Date: 2025-08-03 17:11:33.984076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424811927d10'
down_revision: Union[str, None] = '0dc808c981c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    property_type_enum = sa.Enum(
        'DETACHED', 'SEMI_DETACHED', 'TERRACED', 'END_OF_TERRACE', 'BUNGALOW', 'MAISONETTE', 'FLAT',
        'DUPLEX', 'TRIPLEX', 'PENTHOUSE', 'STUDIO', 'COTTAGE', 'VILLA', 'TOWNHOUSE', 'CHALET',
        name='propertytype'
    )
    property_type_enum.create(op.get_bind(), checkfirst=True)  # <-- Add this line

    
    op.execute("UPDATE unit SET type = 'SEMI_DETACHED' WHERE LOWER(type) = 'semi-detached'")
    op.execute("UPDATE unit SET type = 'TERRACED' WHERE LOWER(type) = 'terrace'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('DETACHED', 'SEMI_DETACHED', 'TERRACED', 'END_OF_TERRACE', 'BUNGALOW', 'MAISONETTE', 'FLAT', 'DUPLEX', 'TRIPLEX', 'PENTHOUSE', 'STUDIO', 'COTTAGE', 'VILLA', 'TOWNHOUSE', 'CHALET', name='propertytype'),
               existing_nullable=True, postgresql_using="type::propertytype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    property_type_enum = sa.Enum(
        'DETACHED', 'SEMI_DETACHED', 'TERRACED', 'END_OF_TERRACE', 'BUNGALOW', 'MAISONETTE', 'FLAT',
        'DUPLEX', 'TRIPLEX', 'PENTHOUSE', 'STUDIO', 'COTTAGE', 'VILLA', 'TOWNHOUSE', 'CHALET',
        name='propertytype'
    )
    property_type_enum.drop(op.get_bind(), checkfirst=True)  # <-- Add this line
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'type',
               existing_type=sa.Enum('DETACHED', 'SEMI_DETACHED', 'TERRACED', 'END_OF_TERRACE', 'BUNGALOW', 'MAISONETTE', 'FLAT', 'DUPLEX', 'TRIPLEX', 'PENTHOUSE', 'STUDIO', 'COTTAGE', 'VILLA', 'TOWNHOUSE', 'CHALET', name='propertytype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
