"""auto

Revision ID: 47c102d5f1d1
Revises: ac8b629a1312
Create Date: 2025-08-29 07:37:20.790036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c102d5f1d1'
down_revision: Union[str, None] = 'ac8b629a1312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('media_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'payment', 'mediafile', ['media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'media_id')
    # ### end Alembic commands ###
