"""auto

Revision ID: 77e6c4a410b7
Revises: 47c102d5f1d1
Create Date: 2026-01-19 14:39:20.521981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77e6c4a410b7'
down_revision: Union[str, None] = '47c102d5f1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documenttemplate', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('signeddocument', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signeddocument', 'description')
    op.drop_column('documenttemplate', 'description')
    # ### end Alembic commands ###
