"""auto

Revision ID: 79473898a8e5
Revises: 424811927d10
Create Date: 2025-08-06 16:24:17.145076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79473898a8e5'
down_revision: Union[str, None] = '424811927d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    paymentduration = sa.Enum('MONTHLY', 'QUARTERLY', 'BI_ANNUALLY', 'ANNUALLY', name='paymentduration')
    paymentduration.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('payment_duration', paymentduration, nullable=True))
    op.add_column('unit', sa.Column('warranty_period', sa.Integer(), nullable=True))
    op.alter_column('unit', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('unit', 'warranty_period')
    op.drop_column('unit', 'payment_duration')
    # ### end Alembic commands ###
