"""auto

Revision ID: 815c13d21075
Revises: 2aafdf82fc7c
Create Date: 2025-06-16 15:32:53.633165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '815c13d21075'
down_revision: Union[str, None] = '2aafdf82fc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signeddocument', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('signeddocument', 'agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('signeddocument', 'agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('signeddocument', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
