"""auto

Revision ID: a340e769f0c2
Revises: e2ef777b5c4e
Create Date: 2025-08-12 12:40:21.671405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a340e769f0c2'
down_revision: Union[str, None] = 'e2ef777b5c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediafile', sa.Column('unit_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'mediafile', 'unit', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mediafile', type_='foreignkey')
    op.drop_column('mediafile', 'unit_id')
    # ### end Alembic commands ###
