"""auto

Revision ID: b3bf9c823e6a
Revises: a340e769f0c2
Create Date: 2025-08-12 12:44:07.259763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bf9c823e6a'
down_revision: Union[str, None] = 'a340e769f0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediafile', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.add_column('mediafile', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'mediafile', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'mediafile', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mediafile', type_='foreignkey')
    op.drop_constraint(None, 'mediafile', type_='foreignkey')
    op.drop_column('mediafile', 'user_id')
    op.drop_column('mediafile', 'project_id')
    # ### end Alembic commands ###
